import type { Metadata } from "next"; //export type from next.js 
//^^ just Typescript for debuging 
import { Geist, Geist_Mono } from "next/font/google"; //google fonts
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ //define var name geistMono for css style
  variable: "--font-geist-mono", // define the css variable to use geist_mono 
  subsets: ["latin"], // latin line style 
  // later we can use it like this 
  // font-family: var(--font-geist-sans); 

});

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
  // SEO (Google) Search engine optimization, The primary goal is to rank higher for relevant keywords to attract more targeted traffic , without paying to ads 
  // this funtion is used to set the metadata for the page, which is used by search engines and social media platforms to display information about the page, such as the title and description.  
};

export default function RootLayout({
  // this function is used to define the layout of the page, which is used to wrap the content of the page. 
  // is name ROOTLAYOUT its in / directory main one 
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
